### ISSUE TITLE
Error on compile with gergoplex

### ISSUE THREAD

**Issue by Hate9** [stasmarkin/sm_td#1]
Not sure if this is specific to my keyboard or not (it doesn't look like it should be, but I figured I'd mention my model anyway).
The entire compile process works fine until it gets to `Linking: .build/gboards_gergoplex_haze.elf` (my keymap is called haze).
The error it throws is:
```
 |
 | /usr/bin/avr-ld: /tmp/ccRgBJPD.ltrans0.ltrans.o: in function `.Loc.1426':
 | /home/mabel/qmk_firmware/./keyboards/gboards/gergoplex/keymaps/haze/sm_td.h:294:(.text.smtd_next_stage+0xc6): undefined reference to `defer_exec'
 | /usr/bin/avr-ld: /tmp/ccRgBJPD.ltrans0.ltrans.o:/home/mabel/qmk_firmware/./keyboards/gboards/gergoplex/keymaps/haze/sm_td.h:298:(.text.smtd_next_stage+0xdc): undefined reference to `cancel_deferred_exec'
 | collect2: error: ld returned 1 exit status
 | 
make: *** [builddefs/common_rules.mk:280: .build/gboards_gergoplex_haze.elf] Error 1
```

I am using the most recent version of the QMK firmware from the repo.

**Comment by stasmarkin** [comment]
Forgot to mention about DEFERRED_EXEC in documentation. All my keyboards have enabled that lib by default.
Please, see updated version of Installation guide sections 1 and  2. You need to add DEFERRED_EXEC_ENABLE = true to rules.mk add put `#define MAX_DEFERRED_EXECUTORS 10` (or more than 10) to your `config.h` file.

Please, leave a feedback if it helps

**Comment by Hate9** [comment]
Thanks!
What determines how many max deferred executors I need?

**Comment by Hate9** [comment]
Oh dear, it's still not working after adding those lines?
Same error, and I'm doing a clean build so that shouldn't be happening.

**Comment by Hate9** [comment]
(If you want to make sure I'm not doing something wrong, you can find my layout at https://gitlab.com/MayESchaefer/gergoplex-layout/-/tree/smtd, though I apologize in advance for my keymap being extremely overcomplicated)

**Comment by stasmarkin** [comment]
You need to change `DEFERRED_EXEC_ENABLE = true` to `DEFERRED_EXEC_ENABLE = yes`
I hope that would help

**Comment by stasmarkin** [comment]
> What determines how many max deferred executors I need?

The are 10 possibly active state machine in sm_td, it's hardcoded but I will rewrite it later. Each state machine need a single deffered executor. So, it's better to be at least 10 plus a little more for other users usage (if user is also use deffer exec in other features).

If there would be a lack of executors, some state machines may stuck in their states. For example, hold action may not be recognized if you hold a key long enough.

**Comment by Hate9** [comment]
Oh dear, of course it was something tiny and silly like that 😅
Thinks so much!

**Comment by stasmarkin** [comment]
Have you succeed with deferred exec? Can I close the issue?

**Comment by Hate9** [comment]
Oh! Yeah, sorry, yes it's working now!

**Comment by stasmarkin** [comment]
Since you are the first person to try that lib, could you please leave a short feedback to my email (stasmarkin at gmail com) after you get used to that lib. Was that useful? Did it solve any problem for you? etc
Thanks in advance!
