### ISSUE TITLE
error: Implicit declaration of function printf in sm_td.h

### ISSUE THREAD

**Issue by soitchy** [stasmarkin/sm_td#12]
When following debugging documentation, I get a couple of errors regarding printf and snprintf.

I'm curious about the `#include "print.h` when SMTD_DEBUG_ENABLED is defined. Not sure where this exists? Including <stdio.h> of course resolves the problem, but also adds a lot of bytes to memory.

**Comment by stasmarkin** [comment]
Well, I've just followed this guide https://github.com/qmk/qmk_firmware/blob/master/docs/faq_debug.md for debugging qmk. 
In my repo it's located at `quantum/logging/print.h`

**Comment by soitchy** [comment]
Updating QMK fixed this for me.

**Comment by stasmarkin** [comment]
updated wiki page
