### ISSUE TITLE
Describe the default value for each configs

### ISSUE THREAD

**Issue by azzamsa** [stasmarkin/sm_td#16]
Hi, 👋🏽 

Would you like to add the default value for each option mentioned here https://github.com/stasmarkin/sm_td/wiki/2.2:-Customization-guide:-Timeouts-per-key ?

Thanks for `sm_td` 🥞

**Comment by binduwavell** [comment]
Looks like defaults are listed as a function of tapping term?

**Comment by stasmarkin** [comment]
@azzamsa 
There are default values for every global timeout. They are relative to QMK's TAPPING_TERM:

    SMTD_GLOBAL_TAP_TERM (default is TAPPING_TERM)
    SMTD_GLOBAL_FOLLOWING_TAP_TERM (default is TAPPING_TERM)
    SMTD_GLOBAL_SEQUENCE_TERM (default is TAPPING_TERM / 2)
    SMTD_GLOBAL_RELEASE_TERM (default is TAPPING_TERM / 4)
