### ISSUE TITLE
Installation Guide includes incorrect information

### ISSUE THREAD

**Issue by Hate9** [stasmarkin/sm_td#2]
The Installation Guide page on the wiki includes the following lines of demo code:
```
switch (keycode) {
    case CKC_SPACE: {
        switch (CUSTOM_KEYCODE_1) {
```
Whereas the customization guide instead includes the lines:
```
switch (keycode) {
    case CUSTOM_KEYCODE_1: {
        switch (action) {
```
Presumably the lines in the latter are the correct ones (since they actually compile, and the former don't, nor make any sense).

**Comment by stasmarkin** [comment]
Thank you! You are totally right, corrected wiki
