### ISSUE TITLE
Compatiablity with vim

### ISSUE THREAD

**Issue by realYushi** [stasmarkin/sm_td#7]
Hi, your project is working very well and can trigger the home how mode every time. but when i uas it in vim with dw to delete a word, it trigger the home row mode directly. any workaround?

**Comment by stasmarkin** [comment]
Try lowering `SMTD_TIMEOUT_RELEASE` for D macro. By default it is `TAPPING_TERM / 4` and `TAPPING_TERM` is 200 by default. So to configure `SMTD_TIMEOUT_RELEASE` you need to add the following code to your `keymap.c:

```
uint32_t get_smtd_timeout(uint16_t keycode, smtd_timeout timeout) {
    if (keycode == CKC_D && timeout == SMTD_TIMEOUT_RELEASE) return 35;

    return get_smtd_timeout_default(timeout);
}
```

Try different values from 1 to `TAPPING_TERM / 4` (50 by default). The smaller the number, the less accurate the D macro will be for other combos. So you need the biggest number that will work for you for D+W keystrokes.
